### ISSUE TITLE
Считывание кол-ва денег на карте

### ISSUE THREAD

**Issue by SomeoneDude666** [SomeoneDude666/homework-24#1]
Уже долго пытаюсь решить эту задачу и чем больше над ней сижу тем больше нарастает чувство, что я делаю все не так.
Логика такая:
Я вынес все селекторы в класс DashboardPage.
Если написать тест в DashboardPage, то он работает, но из него ничего не сделать return.
В DashboardPage у меня селектор 
`private SelenideElement secondCardInfo = $("[data-test-id='0f3f5c2a-249e-4c3d-8287-09f7a039391d']");`
Если его использовать в DashboardPage он все прекрасно находит, но когда я вызываю гетер от этого селектора в MoneyTransferTest
`DashboardPage dashboardPage = new DashboardPage();
String infoBoforeOperation = dashboardPage.getSecondCardInfo().getValue();`
то я получаю null. так же если использую метод из DashboardPage
`public int readSecondCardMoney() {
        String before[] = secondCardInfo.getValue().toString().split(": ");
        String before2[] = before[1].split(" ");
        return Integer.parseInt(before2[0]);`
он прекрасно работает в DashboardPage, но при вызове его в MoneyTransferTest
`dashboardPage.readSecondCardMoney();`
то опять получаю null.

**Comment by ArRomanov** [comment]
Во-первых, если у вас проблема, то ссылку на ишью лучше прислать в чат и разобраться быстрее, чем отправить ишью вместе с недоделанной домашкой.
Во-вторых, методом getValue вы не получите текст элемента, вы можете получить только значение атрибута value, если он есть у элемента. Вам нужно использовать метод getText.
И в-третьих, нужно использовать локаторы, находясь на той странице, где располагаются эти элементы.

Лучше пишите в slack, чтобы обсудить более подробно, что у вас не получается
